### PR TITLE
fix stabilization issue

### LINKED ISSUE #118: Switching stabilization mode has no effect on actual stabilization mode
Setting the stabilization mode in the app only seems to set the device stabilization mode to `OFF`.

When setting the stabilization modes via settings, the icon shows that stabilization is being applied, yet the camera stabilization modes are not actually being set. Watching the captureRequestKey `android.control.videoStabilizationMode` with command:
```
adb shell cmd media.camera watch start -m android.control.videoStabilizationMode && adb shell cmd media.camera watch live
```

shows the following:

```
0:com.google.jetpackcamera  f0:459481377967489ns:             REQ: output stream ids: 0
0:com.google.jetpackcamera  f0:459481377967489ns:             REQ:android.control.videoStabilizationMode: [OFF]
0:com.google.jetpackcamera  f0:459481447648014ns:                            RES:android.control.videoStabilizationMode: [OFF]
0:com.google.jetpackcamera  f0:459503276505505ns:             REQ: output stream ids: 0
0:com.google.jetpackcamera  f0:459503276505505ns:             REQ:android.control.videoStabilizationMode: [OFF]
0:com.google.jetpackcamera  f0:459503348003582ns:                            RES:android.control.videoStabilizationMode: [OFF]
```

### PR DESCRIPTION
**Pull request by Kimblebee**
fixes #118 
image

`adb shell cmd media.camera watch start -m android.control.videoStabilizationMode && adb shell cmd media.camera watch live`

note the changes when applied in default settings currently requires the app to be relaunched to take effect

### CODE REVIEW

File: domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/CameraXCameraUseCase.kt [hunk 1]
```diff
@@ -496,12 +496,9 @@ constructor(
 
         // set video stabilization
 
-        if (shouldVideoBeStabilized(sessionSettings, supportedStabilizationMode)) {
-            val isStabilized = when (sessionSettings.stabilizeVideoMode) {
-                Stabilization.ON -> true
-                Stabilization.OFF, Stabilization.UNDEFINED -> false
```
Comment (temcguir) [inline domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/CameraXCameraUseCase.kt:502]: Can we remove the similar logic in `createPreviewUseCase`?

**Review by temcguir — APPROVED** [review]
This looks good for now to fix the bug. We'll need to discuss how to enable stabilization when returning from settings rather than requiring a restart of the app to enable it.
